[mypy]
ignore_missing_imports = True
exclude = venv/.*,.*/venv/.*,.*/\.venv/.*,.*/site-packages/.*,src/story_protocol_python_sdk\.egg-info/.*
namespace_packages = True
packages = story_protocol_python_sdk
mypy_path = src

[mypy-story_protocol_python_sdk.*]
ignore_missing_imports = True

[mypy-src.story_protocol_python_sdk.*]
ignore_missing_imports = True

[mypy-tests.*]
ignore_missing_imports = True

[mypy-tests.demo.*]
ignore_missing_imports = True
